### ISSUE TITLE
Request Support for SM-A750F/DS

### ISSUE THREAD

**Issue by DeadPool-4422** [eurekadevelopment/Eureka-Kernel-Exynos7885-Q-R-S#4]
Hello there

I noticed that the Eureka Kernel currently doesn't support the Samsung SM-A750F/DS (a7y18lte) , which uses the Exynos 7885 processor - the same one used in several devices that the kernel does support. It'd be great if you could consider extending support to this device.

Additionally, I found a kernel tree for the SM-A750F/DS on GitHub. It isn't up-to-date, and it could probably do with some cleaning up, but it might serve as a starting point. You can find it here: https://github.com/DeadPool-4422/kernel_samsung_a7y18lte

Adding support for this device could help out a bunch of us who use the SM-A750F/DS. I appreciate your consideration and I'm looking forward to hearing back from you.

In case you need anything from the device i can provide it, i also have some details i collected from the device at 
https://github.com/DeadPool-4422/a7y18lte-Resources 
hope you find it useful

Thanks,
Have A Great Day

**Comment by kevios12** [comment]
Hi,

sorry, we doesnt support any other Phone which we are already. The fact is, lack of Time in our Team due to Jobs and Study.

Dear, Kevios12

**Comment by animegamer4422** [comment]
Thanks for your time
Could you point me to some resource using which I can start to understand things and provide support for the device myself 

I understand it might be hard to work on these hobby projects due to the hectic lifestyle
Just make sure you guys maintain a good physique and a fresh mind 
Take care
