### ISSUE TITLE
error: cannot combine with previous 'void' declaration specifier

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [eurekadevelopment/Eureka-Kernel-Exynos7885-Q-R-S#8]
buildd/sources/include/linux/nmi.h:94:20: error: cannot combine with previous 'void' declaration specifier
static inline void void sl_softirq_entry(const char *, void *) { }

in clang android-12.0-r416183b/

**Comment by EliasTheGrandMasterOfMistakes** [comment]
what is the clang recommended for this kernel?

**Comment by kevios12** [comment]
> what is the clang recommended for this kernel?

Neutron Clang (clang 18 or higher)
